# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crm-api/billing_config_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rpc.common import common_pb2 as common_dot_common__pb2
from . import billing_config_entity_pb2 as crm__api_dot_billing__config__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$crm-api/billing_config_service.proto\x12\npb_crm_api\x1a\x13\x63ommon/common.proto\x1a#crm-api/billing_config_entity.proto\"*\n\x14\x46indBillingConfigReq\x12\x12\n\naccount_id\x18\x01 \x01(\t\"H\n\x14\x46indBillingConfigRsp\x12\x30\n\x06\x63onfig\x18\x01 \x01(\x0b\x32 .pb_crm_api.AccountBillingConfig\"0\n\x19\x42\x61tchFindBillingConfigReq\x12\x13\n\x0b\x61\x63\x63ount_ids\x18\x01 \x03(\t\"N\n\x19\x42\x61tchFindBillingConfigRsp\x12\x31\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32 .pb_crm_api.AccountBillingConfig\"}\n\x1e\x43reateBillingConfigApprovalReq\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x19\n\x11month_upper_limit\x18\x03 \x01(\x03\x12\r\n\x05state\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"5\n\x1e\x43reateBillingConfigApprovalRsp\x12\x13\n\x0b\x61pproval_id\x18\x01 \x01(\t2\xe2\x02\n\x14\x42illingConfigService\x12u\n\x1b\x43reateBillingConfigApproval\x12*.pb_crm_api.CreateBillingConfigApprovalReq\x1a*.pb_crm_api.CreateBillingConfigApprovalRsp\x12[\n\x15RetrieveBillingConfig\x12 .pb_crm_api.FindBillingConfigReq\x1a .pb_crm_api.FindBillingConfigRsp\x12j\n\x1a\x42\x61tchRetrieveBillingConfig\x12%.pb_crm_api.BatchFindBillingConfigReq\x1a%.pb_crm_api.BatchFindBillingConfigRsp\x1a\n\xc8\xab\x91M\x14\xf0\xab\x91M\x00\x42Z\n#com.starrocks.cloud.crm.api.serviceB\x12\x42illingConfigProtoZ\x1fproto/gen-pb/crm-api;pb_crm_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crm_api.billing_config_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.starrocks.cloud.crm.api.serviceB\022BillingConfigProtoZ\037proto/gen-pb/crm-api;pb_crm_api'
  _BILLINGCONFIGSERVICE._options = None
  _BILLINGCONFIGSERVICE._serialized_options = b'\310\253\221M\024\360\253\221M\000'
  _FINDBILLINGCONFIGREQ._serialized_start=110
  _FINDBILLINGCONFIGREQ._serialized_end=152
  _FINDBILLINGCONFIGRSP._serialized_start=154
  _FINDBILLINGCONFIGRSP._serialized_end=226
  _BATCHFINDBILLINGCONFIGREQ._serialized_start=228
  _BATCHFINDBILLINGCONFIGREQ._serialized_end=276
  _BATCHFINDBILLINGCONFIGRSP._serialized_start=278
  _BATCHFINDBILLINGCONFIGRSP._serialized_end=356
  _CREATEBILLINGCONFIGAPPROVALREQ._serialized_start=358
  _CREATEBILLINGCONFIGAPPROVALREQ._serialized_end=483
  _CREATEBILLINGCONFIGAPPROVALRSP._serialized_start=485
  _CREATEBILLINGCONFIGAPPROVALRSP._serialized_end=538
  _BILLINGCONFIGSERVICE._serialized_start=541
  _BILLINGCONFIGSERVICE._serialized_end=895
# @@protoc_insertion_point(module_scope)
