# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import billing_config_service_pb2 as crm__api_dot_billing__config__service__pb2


class BillingConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBillingConfigApproval = channel.unary_unary(
                '/pb_crm_api.BillingConfigService/CreateBillingConfigApproval',
                request_serializer=crm__api_dot_billing__config__service__pb2.CreateBillingConfigApprovalReq.SerializeToString,
                response_deserializer=crm__api_dot_billing__config__service__pb2.CreateBillingConfigApprovalRsp.FromString,
                )
        self.RetrieveBillingConfig = channel.unary_unary(
                '/pb_crm_api.BillingConfigService/RetrieveBillingConfig',
                request_serializer=crm__api_dot_billing__config__service__pb2.FindBillingConfigReq.SerializeToString,
                response_deserializer=crm__api_dot_billing__config__service__pb2.FindBillingConfigRsp.FromString,
                )
        self.BatchRetrieveBillingConfig = channel.unary_unary(
                '/pb_crm_api.BillingConfigService/BatchRetrieveBillingConfig',
                request_serializer=crm__api_dot_billing__config__service__pb2.BatchFindBillingConfigReq.SerializeToString,
                response_deserializer=crm__api_dot_billing__config__service__pb2.BatchFindBillingConfigRsp.FromString,
                )


class BillingConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBillingConfigApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveBillingConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRetrieveBillingConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBillingConfigApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBillingConfigApproval,
                    request_deserializer=crm__api_dot_billing__config__service__pb2.CreateBillingConfigApprovalReq.FromString,
                    response_serializer=crm__api_dot_billing__config__service__pb2.CreateBillingConfigApprovalRsp.SerializeToString,
            ),
            'RetrieveBillingConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveBillingConfig,
                    request_deserializer=crm__api_dot_billing__config__service__pb2.FindBillingConfigReq.FromString,
                    response_serializer=crm__api_dot_billing__config__service__pb2.FindBillingConfigRsp.SerializeToString,
            ),
            'BatchRetrieveBillingConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRetrieveBillingConfig,
                    request_deserializer=crm__api_dot_billing__config__service__pb2.BatchFindBillingConfigReq.FromString,
                    response_serializer=crm__api_dot_billing__config__service__pb2.BatchFindBillingConfigRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb_crm_api.BillingConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BillingConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBillingConfigApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb_crm_api.BillingConfigService/CreateBillingConfigApproval',
            crm__api_dot_billing__config__service__pb2.CreateBillingConfigApprovalReq.SerializeToString,
            crm__api_dot_billing__config__service__pb2.CreateBillingConfigApprovalRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveBillingConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb_crm_api.BillingConfigService/RetrieveBillingConfig',
            crm__api_dot_billing__config__service__pb2.FindBillingConfigReq.SerializeToString,
            crm__api_dot_billing__config__service__pb2.FindBillingConfigRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchRetrieveBillingConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb_crm_api.BillingConfigService/BatchRetrieveBillingConfig',
            crm__api_dot_billing__config__service__pb2.BatchFindBillingConfigReq.SerializeToString,
            crm__api_dot_billing__config__service__pb2.BatchFindBillingConfigRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
