# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crm-api/billing_config_entity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#crm-api/billing_config_entity.proto\x12\npb_crm_api\"\x95\x01\n\x14\x41\x63\x63ountBillingConfig\x12\x11\n\tconfig_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x19\n\x11month_upper_limit\x18\x03 \x01(\x03\x12\x13\n\x0b\x65xpire_time\x18\x04 \x01(\x03\x12&\n\x05state\x18\x05 \x01(\x0e\x32\x17.pb_crm_api.ConfigState*N\n\x0b\x43onfigState\x12\x18\n\x14UNKNOWN_CONFIG_STATE\x10\x00\x12\x11\n\rCONFIG_ENABLE\x10\x01\x12\x12\n\x0e\x43ONFIG_DISABLE\x10\x02\x42_\n\"com.starrocks.cloud.crm.api.entityB\x18\x42illingConfigEntityProtoZ\x1fproto/gen-pb/crm-api;pb_crm_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crm_api.billing_config_entity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\"com.starrocks.cloud.crm.api.entityB\030BillingConfigEntityProtoZ\037proto/gen-pb/crm-api;pb_crm_api'
    _CONFIGSTATE._serialized_start = 203
    _CONFIGSTATE._serialized_end = 281
    _ACCOUNTBILLINGCONFIG._serialized_start = 52
    _ACCOUNTBILLINGCONFIG._serialized_end = 201
# @@protoc_insertion_point(module_scope)
