# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crm-api/contract_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import contract_entity_pb2 as crm__api_dot_contract__entity__pb2
from rpc.common import common_pb2 as common_dot_common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x63rm-api/contract_service.proto\x12\npb_crm_api\x1a\x1d\x63rm-api/contract_entity.proto\x1a\x13\x63ommon/common.proto\"s\n\x19\x43reateContractApprovalReq\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x14\n\x0c\x65xpired_time\x18\x03 \x01(\x03\x12\r\n\x05state\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"0\n\x19\x43reateContractApprovalRsp\x12\x13\n\x0b\x61pproval_id\x18\x01 \x01(\t\":\n\x0eNewContractReq\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65xpired_time\x18\x02 \x01(\x03\".\n\x0eNewContractRsp\x12\x1c\n\x14\x63ontract_customer_id\x18\x01 \x01(\t\"-\n\x17\x46indContractCustomerReq\x12\x12\n\naccount_id\x18\x01 \x01(\t\"I\n\x17\x46indContractCustomerRsp\x12.\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x1c.pb_crm_api.ContractCustomer\"2\n\x1c\x42\x61tchFindContractCustomerReq\x12\x12\n\naccount_id\x18\x01 \x03(\t\"N\n\x1c\x42\x61tchFindContractCustomerRsp\x12.\n\x08\x63ustomer\x18\x01 \x03(\x0b\x32\x1c.pb_crm_api.ContractCustomer2\xe0\x02\n\x0f\x43ontractService\x12\x66\n\x16\x43reateContractApproval\x12%.pb_crm_api.CreateContractApprovalReq\x1a%.pb_crm_api.CreateContractApprovalRsp\x12\x64\n\x18RetrieveContractCustomer\x12#.pb_crm_api.FindContractCustomerReq\x1a#.pb_crm_api.FindContractCustomerRsp\x12s\n\x1d\x42\x61tchRetrieveContractCustomer\x12(.pb_crm_api.BatchFindContractCustomerReq\x1a(.pb_crm_api.BatchFindContractCustomerRsp\x1a\n\xc8\xab\x91M\x14\xf0\xab\x91M\x00\x42U\n#com.starrocks.cloud.crm.api.serviceB\rContractProtoZ\x1fproto/gen-pb/crm-api;pb_crm_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crm_api.contract_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n#com.starrocks.cloud.crm.api.serviceB\rContractProtoZ\037proto/gen-pb/crm-api;pb_crm_api'
    _CONTRACTSERVICE._options = None
    _CONTRACTSERVICE._serialized_options = b'\310\253\221M\024\360\253\221M\000'
    _CREATECONTRACTAPPROVALREQ._serialized_start = 98
    _CREATECONTRACTAPPROVALREQ._serialized_end = 213
    _CREATECONTRACTAPPROVALRSP._serialized_start = 215
    _CREATECONTRACTAPPROVALRSP._serialized_end = 263
    _NEWCONTRACTREQ._serialized_start = 265
    _NEWCONTRACTREQ._serialized_end = 323
    _NEWCONTRACTRSP._serialized_start = 325
    _NEWCONTRACTRSP._serialized_end = 371
    _FINDCONTRACTCUSTOMERREQ._serialized_start = 373
    _FINDCONTRACTCUSTOMERREQ._serialized_end = 418
    _FINDCONTRACTCUSTOMERRSP._serialized_start = 420
    _FINDCONTRACTCUSTOMERRSP._serialized_end = 493
    _BATCHFINDCONTRACTCUSTOMERREQ._serialized_start = 495
    _BATCHFINDCONTRACTCUSTOMERREQ._serialized_end = 545
    _BATCHFINDCONTRACTCUSTOMERRSP._serialized_start = 547
    _BATCHFINDCONTRACTCUSTOMERRSP._serialized_end = 625
    _CONTRACTSERVICE._serialized_start = 628
    _CONTRACTSERVICE._serialized_end = 980
# @@protoc_insertion_point(module_scope)
