# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crm-api/contract_entity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63rm-api/contract_entity.proto\x12\npb_crm_api\"\\\n\x14\x43ontractCustomerCond\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x30\n\x05state\x18\x02 \x01(\x0e\x32!.pb_crm_api.ContractCustomerState\"\x8c\x01\n\x10\x43ontractCustomer\x12\x1c\n\x14\x63ontract_customer_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x30\n\x05state\x18\x03 \x01(\x0e\x32!.pb_crm_api.ContractCustomerState\x12\x14\n\x0c\x65xpired_time\x18\x04 \x01(\x03*\x85\x01\n\x15\x43ontractCustomerState\x12#\n\x1f\x43ONTRACT_CUSTOMER_STATE_UNKNOWN\x10\x00\x12\"\n\x1e\x43ONTRACT_CUSTOMER_STATE_ENABLE\x10\x01\x12#\n\x1f\x43ONTRACT_CUSTOMER_STATE_DISABLE\x10\x02\x42Z\n\"com.starrocks.cloud.crm.api.entityB\x13\x43ontractEntityProtoZ\x1fproto/gen-pb/crm-api;pb_crm_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crm_api.contract_entity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.starrocks.cloud.crm.api.entityB\023ContractEntityProtoZ\037proto/gen-pb/crm-api;pb_crm_api'
  _CONTRACTCUSTOMERSTATE._serialized_start=283
  _CONTRACTCUSTOMERSTATE._serialized_end=416
  _CONTRACTCUSTOMERCOND._serialized_start=45
  _CONTRACTCUSTOMERCOND._serialized_end=137
  _CONTRACTCUSTOMER._serialized_start=140
  _CONTRACTCUSTOMER._serialized_end=280
# @@protoc_insertion_point(module_scope)
